stages:
  - build

build_docker_image:
  stage: build
  image: docker:24.0.5-cli
  services:
    - name: docker:24.0.5-dind
  before_script:
    - docker info
    - docker buildx create --use --name multiarch-builder || docker buildx use multiarch-builder
    - docker buildx inspect --bootstrap
  script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/386 -t crispybitsapp/castor:dev --push .
  only:
    - dev
