services:
  castor:
    container_name: castor
    image: crispybitsapp/castor:alpha5
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: ${TIMEZONE}
      LOG_PATH: "/srv/logs/castor.log"
      AUDIO_SOURCE_PATH: ${AUDIO_SOURCE_PATH}
      AUDIO_PLAYLIST_PATH: ${AUDIO_PLAYLIST_PATH}
      AUDIO_RECORD_PATH: ${AUDIO_RECORD_PATH}
      AUDIO_FALLBACK_PATH: ${AUDIO_FALLBACK_PATH}
      PRELOAD_TIME_FILE: ${PRELOAD_TIME_FILE}
      PRELOAD_TIME_STREAM: ${PRELOAD_TIME_STREAM}
      PRELOAD_TIME_FALLBACK: ${PRELOAD_TIME_FALLBACK}
      SILENCE_THRESHOLD: ${SILENCE_THRESHOLD}
      SILENCE_START_DURATION: ${SILENCE_START_DURATION}
      SILENCE_STOP_DURATION: ${SILENCE_STOP_DURATION}
      IN_DEVICE_NAME: ${IN_DEVICE_NAME}
      OUT_DEVICE_NAME: ${OUT_DEVICE_NAME}
      STREAM_OUT_URL: ${STREAM_OUT_URL}
      STREAM_OUT_METADATA_URL: ${STREAM_OUT_METADATA_URL}
      STREAM_OUT_NAME: ${STREAM_OUT_NAME}
      STREAM_OUT_DESCRIPTION: ${STREAM_OUT_DESCRIPTION}
      STREAM_OUT_GENRE: ${STREAM_OUT_GENRE}
      STREAM_OUT_HREF: ${STREAM_OUT_HREF}
      PROGRAM_URL: ${PROGRAM_URL}
      PLAYLIST_URL: ${PLAYLIST_URL}
      PLAYLOG_URL: ${PLAYLOG_URL}
      PLAYLIST_TOKEN: ${PLAYLIST_TOKEN}
      TCP_PORT: ${TCP_PORT}
    volumes:
      - ./audio:/srv/audio
      - ./logs:/srv/logs
    devices:
      - /dev/snd:/dev/snd
    ports:
      - "${TCP_PORT}:${TCP_PORT}/tcp"

volumes:
  audio:
  logs:
