services:
  castor:
    container_name: castor
    image: crispybitsapp/castor:alpha5
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./audio:/srv/audio
      - ./logs:/srv/logs
      - ./socket:/srv/socket
      - /opt/aura/audio:/opt/aura/audio
      - /opt/MP3:/opt/MP3
    devices:
      - /dev/snd:/dev/snd
    environment:
      LOG_PATH: "/srv/logs/castor.log"
      SOCKET_PATH: "/srv/socket/castor.sock"
      AUDIO_SOURCE_PATH: ${AUDIO_SOURCE_PATH}
      AUDIO_PLAYLIST_PATH: ${AUDIO_PLAYLIST_PATH}
      AUDIO_RECORD_PATH: ${AUDIO_RECORD_PATH}
      AUDIO_FALLBACK_PATH: ${AUDIO_FALLBACK_PATH}
      INPUT_DEVICE: ${INPUT_DEVICE}
      OUTPUT_DEVICE: ${OUTPUT_DEVICE}
      STREAM_OUTPUT_URL: ${STREAM_OUTPUT_URL}
      PROGRAM_URL: ${PROGRAM_URL}
      PLAYLIST_URL: ${PLAYLIST_URL}
      PLAYLOG_URL: ${PLAYLOG_URL}
      PLAYLIST_TOKEN: ${PLAYLIST_TOKEN}

volumes:
  audio:
  logs:
  socket:
