services:
  lap:
    container_name: lap
    image: crispybitsapp/lap:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - socket:/srv/socket
    devices:
      - /dev/snd:/dev/snd
    environment:
      SOCKET_PATH: "/srv/socket/engine.sock"
      AURA_ENGINE_INPUT_DEVICE: ${AURA_ENGINE_INPUT_DEVICE}
      AURA_ENGINE_OUTPUT_DEVICE: ${AURA_ENGINE_OUTPUT_DEVICE}

volumes:
  socket:
