services:
  lap:
    container_name: lap
    image: crispybitsapp/lap:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - socket:/srv/socket
    devices:
      - /dev/snd:/dev/snd
    environment:
      SOCKET_PATH: "/srv/socket/engine.sock"
      AURA_ENGINE_INPUT_DEVICE: "Soundcraft Signature 12 MTK: USB Audio (hw:0,0)"
      AURA_ENGINE_OUTPUT_DEVICE: "Soundcraft Signature 12 MTK: USB Audio (hw:0,0)"
    working_dir: /app
    command: ["lap"]

volumes:
  socket:
