services:
  castor:
    container_name: castor
    image: crispybitsapp/castor:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: ${TIMEZONE}
      AUDIO_SOURCE_PATH: ${AUDIO_SOURCE_PATH}
      AUDIO_PLAYLIST_PATH: ${AUDIO_PLAYLIST_PATH}
      AUDIO_FALLBACK_PATH: ${AUDIO_FALLBACK_PATH}
      AUDIO_RECORD_PATH: ${AUDIO_RECORD_PATH}
    volumes:
      - ./config:/srv/config:ro
      - ./audio:/srv/audio
      - ./logs:/srv/logs
    devices:
      - /dev/snd:/dev/snd
    ports:
      - "${WEB_CONTROL_PORT}:${WEB_CONTROL_PORT}/tcp"

volumes:
  audio:
  logs:
